# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# 用于SEO

title: 札记
subtitle: >- # this means to ignore newlines until "baseurl:"
  高山仰止，景行行止。虽不能至，然心向往之。
email: 738819904@qq.com
description: >- # this means to ignore newlines until "baseurl:"
     Notes
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://notes.tried.cc" # the base hostname & protocol for your site, e.g. http://example.com

github_username:  zhongwencool

# 用于SEO
twitter:
  username: erl_learn
  card: summary

social:
  name: 邓忠文
  links:
    - https://twitter.com/erl_learn
    - https://weibo.com/zhongwencool
    - https://github.com/zhongwencool
    - https://www.douban.com/people/zhognwencool

google_site_verification: UA-jdwawmK2viL1Do3m87FvVrXYHhvhxV8LgSIHRrn8_vY

lang: "zh-Hans"

author:
  twitter: erl_learn

google_analytics: UA-129364320-1


excerpt_separator: <!--more-->


# Build settings
markdown: kramdown
#theme: minima
theme: jekyll-theme-leap-day
safe: false
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
